name: Size Limit

on:
   pull_request:
   push:
      branches: main

permissions:
   contents: read

jobs:
   size-limit:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [20.x]
      steps:
         - name: Checkout code
           uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.15.4

         - name: Setup Node.js
           uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: pnpm

         - name: Install dependencies and build
           run: |
              pnpm install --frozen-lockfile
              pnpm build

         - name: Run size limit check
           run: pnpm lint:size
